#!/bin/bash
#
# This version works on Plasma 5, but not on Plasma 6
#
#
# Define color and formatting variables
BLUE='\033[0;34m'
BOLD='\033[1m'
RESET='\033[0m'

# Define help message

HELP_MSG='\n--- System-Info ---\n\nDisplay KDE Plasma System Information from the Terminal.\n\nAdd an Application-name to add its information.\nExample:\nsysinfo konsole\n\nClipboard copying on Wayland and X11 supported.\n\nUse -h to show this help\n\n--------------------'

function package_info() {
    rpm -qa 2>/dev/null | grep $1 || dpkg-query -W $1 2>/dev/null || pacman -Qi $1 2>/dev/null || pamac info $1 2>/dev/null || emerge --search $1 2>/dev/null || apk info $1 2>/dev/null || nix-env -q 2>/dev/null | grep $1 || yay -Si $1 2>/dev/null || snap info $1 2>/dev/null || flatpak list 2>/dev/null | grep $1 || flatpak search $1 2>/dev/null
}

function gpudriver() {
    # Check if Nvidia driver is being used
    if lsmod | grep -q "^nvidia "; then
        GPUdriver="driver: NVIDIA prop."
    elif lsmod | grep -q "^nouveau "; then
        GPUdriver="driver: Nouveau"
    elif lspci | grep -iqE "VGA compatible controller: (Intel|Advanced Micro Devices)"; then
        GPUdriver="driver: mesa"
    else
        GPUdriver="driver: unknown"
    fi
}

# Argument loop
# if argument is help, show help
if [[ $# -eq 1 && ( $1 == "-h" || $1 == "--help" ) ]]; then
    echo -e $HELP_MSG && exit 1
# if argument something else, see if its an app
elif [[ $# -eq 1 ]]; then
    # check the app with various package managers
    appvalue=$(package_info $1)
    # if appvalue not existent, app not found. Maybe an exotic package manager is missing, feel free to add it!
    if [ -z "$appvalue" ]; then
      echo "Program not found"
      # Exit the whole script to save time
      exit 1
    else
    appvalue="Specified App:\n$appvalue\n\n"
    fi
fi


# ------ GET SOFTWARE INFO -----

# only echo the combined pretty name of the OS
OSinfo="OS: $(grep 'PRETTY_NAME' /etc/os-release | cut -d '"' -f 2)"

Plasmainfo="KDE Plasma: $(plasmashell --version | awk '{print $2}')"

FWinfo="$(kf5-config --version | grep "KDE Frameworks: ")"

Qtinfo="$(kf5-config --version | grep "Qt: ")"

Kernelinfo="Kernel: $(uname -r)"

# echo session manager, make first letter capital, yes that was nessecary
Compositorinfo="Compositor: $(echo $XDG_SESSION_TYPE)"

# ------- GET HARDWARE INFO ---------

# echo Processor model, remove its own value name ".*: "
CPUinfo="CPU: $(grep 'model name' /proc/cpuinfo | head -1 | sed 's/.*: //'
)"

# echo specific lines from meminfo, shorten value to one decimal place, make it GB
RAMinfo="RAM: $(grep 'MemTotal' /proc/meminfo | awk '{printf "%.1f GB\n", $2/1024/1024}')"

# echo GLXinfo, some strange parameters Ei, cut first two lines, remove "Device:", "everything in brackets" and "TAB" (before the next line)
GPUinfo="GPU: $(glxinfo | grep -Ei 'device|memory' | head -2 | sed -e 's/Device: //g' -e 's/ ([^()]*)//g' -e 's/    //g')"

gpudriver

# ---------------------- Audio Information, Pipewire or Pulseaudio --------------
# Check if user has pipewire installed
if command -v "pipewire -h" >/dev/null 2>&1; then
    AudioInfo="Audio: Pipewire"
elif command -v pulseaudio >/dev/null 2>&1; then
    AudioInfo="Audio: Pulseaudio"
else
    AudioInfo="Audio: unknown"
fi


# ----- OUTPUT AND CLIPBOARD COPY ------

#Visual printing:
printf "$appvalue${BLUE}${BOLD}--- Software --- ${RESET} \n$OSinfo \n$Plasmainfo \n$FWinfo \n$Qtinfo \n$Kernelinfo \n$Compositorinfo \n \n${BLUE}${BOLD}--- Hardware ---${RESET} \n$CPUinfo \n$RAMinfo \n$GPUinfo, $GPUdriver\n$AudioInfo \n \n"


# Clipboard
while true; do
    read -p "Copy to clipboard? (y/n) > " yn
    case $yn in
        [Yy]* ) echo -e "$appvalue--- Software ---\n$OSinfo\n$Plasmainfo\n$FWinfo\n$Qtinfo\n$Kernelinfo\n$Compositorinfo\n\n--- Hardware ---\n$CPUinfo\n$RAMinfo\n$GPUinfo, $GPUdriver\n$AudioInfo"| tee >(wl-copy || xclip -selection clipboard || xsel -ib) >/dev/null && echo -e "\n🗒️ Copied to clipboard!"|| echo "Clipboard command not found. Install wl-clipboard for Wayland or xsel or xclip for X11." && break;;
        [Nn]* ) break;;
        * ) echo "Please answer yes or no.";;
    esac
done
